
export const SAVE_USER = 'SAVE_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const INIT_USER_TYPE = 'INIT_USER_TYPE'
export const SAVE_PROVINCE = 'SAVE_PROVINCE'
export const SAVE_SALARY_ENTS = 'SAVE_SALARY_ENTS'
export const BUSINESS_TYPE = 'BUSINESS_TYPE'
export const COOPERATE_ENT_NAME = 'COOPERATE_ENT_NAME'

export const SAVE_BUTTON = 'SAVE_BUTTON'
